import {
  Code,
  CreditCard,
  Home,
  LayoutDashboard,
  Palette,
  Server,
  Settings,
  Shield,
  User,
} from "lucide-react";

import type { DashboardExtension } from "../../types";

export const userCenterExtension: DashboardExtension = {
  id: "builtin.user-center",
  meta: {
    title: "用户中心",
    description: "核心控制台能力，包括账户、管理与观测功能。",
    version: "1.0.0",
    author: "XWork Tech",
    keywords: ["dashboard", "accounts", "management"],
  },
  routes: [
    {
      id: "dashboard",
      path: "/panel",
      label: "Dashboard",
      description: "专属于你的信息总览",
      icon: Home,
      loader: () => import("./routes/home"),
      match: "startsWith",
      guard: { requireLogin: true },
      redirect: { unauthenticated: "/login" },
      sidebar: { section: "workspace", order: 0 },
    },
    {
      id: "agents",
      path: "/panel/agent",
      label: "Agents",
      description: "管理运行节点",
      icon: Server,
      loader: () => import("./routes/agent"),
      guard: { requireLogin: true },
      redirect: { unauthenticated: "/login" },
      sidebar: { section: "productivity", order: 10 },
      featureFlag: {
        id: "user-center.agent",
        title: "Agent 节点管理",
        description: "启用运行节点管理页面。",
        envVar: "NEXT_PUBLIC_FEATURE_AGENT_MODULE",
        defaultEnabled: true,
      },
    },
    {
      id: "apis",
      path: "/panel/api",
      label: "Integrations",
      description: "统一管理 OpenClaw、Vault 与 AI Gateway",
      icon: Code,
      loader: () => import("./routes/api"),
      guard: { requireLogin: true },
      redirect: { unauthenticated: "/login" },
      sidebar: { section: "productivity", order: 11 },
      featureFlag: {
        id: "user-center.api",
        title: "接口集成",
        description: "启用 OpenClaw、Vault 与 APISIX AI Gateway 集成页面。",
        envVar: "NEXT_PUBLIC_FEATURE_API_MODULE",
        defaultEnabled: true,
      },
    },
    {
      id: "accounts",
      path: "/panel/account",
      label: "Accounts",
      description: "目录与多因素设置",
      icon: User,
      loader: () => import("./routes/account"),
      guard: { requireLogin: true },
      redirect: { unauthenticated: "/login" },
      sidebar: { section: "management", order: 20, hidden: true },
    },
    {
      id: "subscription",
      path: "/panel/subscription",
      label: "Subscription",
      description: "订阅方案与计费规则",
      icon: CreditCard,
      loader: () => import("./routes/subscription"),
      guard: { requireLogin: true },
      redirect: { unauthenticated: "/login" },
      sidebar: { section: "management", order: 21 },
      featureFlag: {
        id: "user-center.subscription",
        title: "订阅与计费",
        description: "启用订阅与计费配置页面。",
        envVar: "NEXT_PUBLIC_FEATURE_SUBSCRIPTION_MODULE",
        defaultEnabled: true,
      },
    },
    {
      id: "ldp",
      path: "/panel/ldp",
      label: "LDP",
      description: "低时延身份平面",
      icon: Shield,
      loader: () => import("./routes/ldp"),
      guard: { requireLogin: true },
      redirect: { unauthenticated: "/login" },
      sidebar: { section: "management", order: 22 },
      featureFlag: {
        id: "user-center.ldp",
        title: "LDP 管理",
        description: "启用低时延身份平面管理模块。",
        envVar: "NEXT_PUBLIC_FEATURE_LDP_MODULE",
        defaultEnabled: false,
      },
    },
    {
      id: "appearance",
      path: "/panel/appearance",
      label: "Appearance",
      description: "个性化主题设置",
      icon: Palette,
      loader: () => import("./routes/theme"),
      guard: { requireLogin: true },
      redirect: { unauthenticated: "/login" },
      sidebar: { section: "preferences", order: 30 },
    },
    {
      path: "/panel/management",
      label: "Management",
      description: "集中化的权限矩阵与用户编排",
      icon: Settings,
      loader: () => import("./routes/management"),
      guard: {
        requireLogin: true,
        roles: ["admin", "operator"] as Array<"admin" | "operator">,
        permissions: [
          "admin.settings.read",
          "admin.users.metrics.read",
          "admin.users.list.read",
          "admin.agents.status.read",
          "admin.blacklist.read",
        ],
      },
      match: "startsWith",
      redirect: { unauthenticated: "/login", forbidden: "/panel" },
      // 对 admin / operator（含由组继承而来的）显示在侧边栏；普通用户看不到，
      // 也进不去。PanelSidebarContent 对每个带 roles 的路由都会跑一次
      // resolveAccess，不通过就整条隐藏，所以取消 hidden 不会把入口暴露给
      // 无权限的人——hidden 原本只是"连有权限的人也不显示"。
      sidebar: { section: "admin", order: 99 },
    },
    {
      id: "ops",
      path: "/panel/ops",
      label: "运营工作台",
      description: "经营状态与账号处置",
      icon: LayoutDashboard,
      loader: () => import("./routes/ops"),
      match: "startsWith",
      guard: {
        requireLogin: true,
        roles: ["admin", "operator"] as Array<"admin" | "operator">,
      },
      redirect: { unauthenticated: "/login", forbidden: "/panel" },
      sidebar: { section: "admin", order: 10 },
    },
    {
      id: "ops-accounts",
      path: "/panel/ops/accounts",
      label: "账号处置台",
      description: "检索账号并执行运营处置",
      icon: LayoutDashboard,
      loader: () => import("./routes/ops"),
      match: "startsWith",
      guard: {
        requireLogin: true,
        roles: ["admin", "operator"] as Array<"admin" | "operator">,
      },
      redirect: { unauthenticated: "/login", forbidden: "/panel" },
      sidebar: { section: "admin", order: 11, hidden: true },
    },
    ...["billing/plans", "billing/ledger", "audit", "system"].map((suffix) => ({
      id: `ops-${suffix.replace("/", "-")}`,
      path: `/panel/ops/${suffix}`,
      label: suffix === "audit" ? "审计与系统" : suffix === "system" ? "系统管理" : suffix === "billing/plans" ? "套餐与订阅" : "账单与对账",
      description: "运营工作台子模块",
      icon: LayoutDashboard,
      loader: () => import("./routes/ops"),
      match: "startsWith" as const,
      guard: {
        requireLogin: true,
        roles: ["admin", "operator"] as Array<"admin" | "operator">,
      },
      redirect: { unauthenticated: "/login", forbidden: "/panel" },
      sidebar: { section: "admin", order: 12, hidden: true },
    })),
  ],
};
